### ISSUE TITLE
Babel-runtime dependency missing

### ISSUE THREAD

**Issue by joshrivers** [CircleOfNice/CoreWorker#44]
#### Description of Feature / Expected vs Actual Behaviour
Under node.js 4.5.0, core-worker 0.3.0 fails to load in require() due to a missing babel-runtime dependency. The dependency was removed in https://github.com/CircleOfNice/CoreWorker/commit/4d8afe2a835c524d5ae4889a47101ba75db8c220 perhaps by accident.

Error Message:

    $ node index.js 
    module.js:327
        throw err;
        ^

    Error: Cannot find module 'babel-runtime/core-js/object/get-prototype-of'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/riversj/Code/test/node_modules/core-worker/lib/DuplexStream.js:7:23)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)

#### Steps to reproduce

    npm install core-worker --save
    echo "var coreworker=require('core-worker');" > index.js
    node index.js 

problem is resolved after:

    npm install babel-runtime
    node index.js 

#### Additional Information

    $ node -v
    v4.5.0

**Comment by nikonovd** [comment]
Thank you for reporting the issue @joshrivers which has been resolved by [CoreWorker 0.3.1](https://github.com/CircleOfNice/CoreWorker/releases/tag/0.3.1)
